### ISSUE TITLE
Installation throws unexpected token error. 

### ISSUE THREAD

**Issue by SK4ndal** [markt-de/puppet-activemq#5]
During installation this error occurs. It seems that with the transition to markt-de forge account some hidden character has been added to some json somewhere. 

``` 
Error: Received a Log attribute with invalid encoding:"unexpected token at '\x1F\x8B\b'"\nBacktrace:
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puppet-7.24.0/lib/puppet/util/log.rb:194:in `newmessage'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puppet-7.24.0/lib/puppet/util/log.rb:319:in `initialize'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puppet-7.24.0/lib/puppet/util/log.rb:87:in `new'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puppet-7.24.0/lib/puppet/util/log.rb:87:in `create'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puppet-7.24.0/lib/puppet/util/logging.rb:9:in `send_log'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puppet-7.24.0/lib/puppet/util/logging.rb:69:in `log_exception'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puppet-7.24.0/lib/puppet/application/face_base.rb:270:in `rescue in main'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puppet-7.24.0/lib/puppet/application/face_base.rb:266:in `main'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puppet-7.24.0/lib/puppet/application.rb:437:in `run_command'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/puppet-7.24.0/lib/puppet/application.rb:421:in `block in run'
Error: Try 'puppet help module install' for usage
```

**Comment by SK4ndal** [comment]
After some testing there seems to be some redirect or other funnybusiness that messes things up. We use librarian-puppet and markt-activemq is the only module that seems to use http instead of https. 

This fails: 
```
puppet module install --version 1.5.0 --target-dir /home/foo/bar/markt-activemq/1.5.0 --module_repository http://forgeapi.puppetlabs.com --modulepath /home/foo/bar/markt-activemq/1.5.0 --module_working_dir /home/foo/bar/markt-activemq/1.5.0 --ignore-dependencies markt-activemq
Notice: Preparing to install into /home/foo/bar/markt-activemq/1.5.0 ...
Notice: Downloading from http://forgeapi.puppetlabs.com ...
Error: unexpected character (after ) at line 1, column 1 [parse.c:724]
Error: Try 'puppet help module install' for usage
```


This works: 
```
puppet module install --version 1.5.0 --target-dir /home/foo/bar/markt-activemq/1.5.0 --module_repository https://forgeapi.puppetlabs.com --modulepath /home/foo/bar/markt-activemq/1.5.0 --module_working_dir /home/foo/bar/markt-activemq/1.5.0 --ignore-dependencies markt-activemq
Notice: Preparing to install into /home/foo/bar/markt-activemq/1.5.0 ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/home/foo/bar/markt-activemq/1.5.0
└── markt-activemq (v1.5.0)
```

**Comment by fraenki** [comment]
I get the same error when trying to download puppetlabs/stdlib, so this is a breakage at the Puppet Forge.
Please report it to the official channels:
